# --------------------------------------------------------------------------------------------------
# 
#

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAuthToken: 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

npmPublishAccess: restricted

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs

enableMessageNames: false

# nmMode: "classic"
