compressionLevel: mixed

enableGlobalCache: false

enableMessageNames: false

nmSelfReferences: false

nodeLinker: node-modules

# npmAuthToken: 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
npmAuthToken: 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

npmPublishAccess: restricted

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.0.0-rc.53.cjs
